// Captured 2026-09-23. Rendered immediately on load and kept for any live fetch that fails.
// Refresh instructions: see README.md.
export const SNAPSHOT = {
  date: '2026-09-23',
  repos: [
    {
      name: 'TouchPortal_Discord_Plugin',
      description: 'Touch Portal Plugin to Interact with Discord',
      stars: 69,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_Discord_Plugin',
      pushedAt: '2026-08-06T20:02:37Z',
    },
    {
      name: 'TouchPortal-HardwareMonitor',
      description: 'Touch Portal plugin with Libre Hardware Monitor built in - exposes every sensor as auto-created states. No third-party app required.',
      stars: 34,
      language: 'C#',
      url: 'https://github.com/spdermn02/TouchPortal-HardwareMonitor',
      pushedAt: '2026-07-09T18:46:32Z',
    },
    {
      name: 'TouchPortal-Dynamic-Icons',
      description: 'Generate Dynamic Icons for Touch Portal based on Actions and 0-100% values.',
      stars: 14,
      language: 'TypeScript',
      url: 'https://github.com/spdermn02/TouchPortal-Dynamic-Icons',
      pushedAt: '2025-05-16T19:32:29Z',
    },
    {
      name: 'TouchPortal_KeyboardMaestro_Plugin',
      description: 'Plugin to interface with Keyboard Maestro',
      stars: 6,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_KeyboardMaestro_Plugin',
      pushedAt: '2024-11-11T22:42:12Z',
    },
    {
      name: 'TouchPortal_ITunes_Plugin',
      description: 'Plugin to control iTunes (windows only for now) directly from Touch Portal',
      stars: 5,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_ITunes_Plugin',
      pushedAt: '2025-01-03T15:59:21Z',
    },
    {
      name: 'TouchPortal_Corsair_iCue',
      description: 'Touch Portal Corsair iCue integration',
      stars: 5,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_Corsair_iCue',
      pushedAt: '2022-06-15T17:04:13Z',
    },
  ],
  more: [
    {
      name: 'TouchPortal_WebpageCapture_Plugin',
      description: 'Snapshot stream chat into an icon directly viewable on Touch Portal',
      stars: 4,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_WebpageCapture_Plugin',
      pushedAt: '2025-03-30T19:39:24Z',
    },
    {
      name: 'TouchPortal_AdvancedHold_Plugin',
      description: 'While a Key is held, update a state every X Seconds until let go. Run actions infinitely ever X Seconds until stopped.',
      stars: 4,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_AdvancedHold_Plugin',
      pushedAt: '2021-11-11T16:33:15Z',
    },
    {
      name: 'TouchPortal_MessageKeyPress',
      description: 'Trigger Keypresses based on a string of text sent in',
      stars: 2,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_MessageKeyPress',
      pushedAt: '2023-12-18T04:08:37Z',
    },
    {
      name: 'TouchPortal_StreamRaiders_Plugin',
      description: 'Plugin for Touch Portal to interact with Stream Raiders',
      stars: 2,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_StreamRaiders_Plugin',
      pushedAt: '2021-11-28T22:12:49Z',
    },
    {
      name: 'TouchPortal_MeldStudio_Plugin',
      description: 'Plugin for Touch Portal to control Meld Studio',
      stars: 1,
      language: null,
      url: 'https://github.com/spdermn02/TouchPortal_MeldStudio_Plugin',
      pushedAt: '2025-08-24T17:30:51Z',
    },
    {
      name: 'TouchPortal_Clownfish_VoiceChanger_Plugin',
      description: 'Interact with Clownfish Voice Changer software',
      stars: 1,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_Clownfish_VoiceChanger_Plugin',
      pushedAt: '2023-01-17T22:21:35Z',
    },
    {
      name: 'TouchPortal-KeyboardKeyCap-Icons-Grey',
      description: 'Icons for Touch Portal in a Keyboard KeyCap style colored Grey',
      stars: 1,
      language: null,
      url: 'https://github.com/spdermn02/TouchPortal-KeyboardKeyCap-Icons-Grey',
      pushedAt: '2020-10-02T19:10:55Z',
    },
    {
      name: 'TouchPortal-Screen-Graphics-Plugin',
      description: 'Display Screen Graphics not only to your Stream but they will actually affect your screen and possible visuals for your gameplay! Make it more interactive.',
      stars: 0,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal-Screen-Graphics-Plugin',
      pushedAt: '2026-04-07T21:57:51Z',
    },
    {
      name: 'TouchPortal_Imgur_Plugin',
      description: 'Plugin to take an Image upload to Imgur and get back the Url of that Image',
      stars: 0,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal_Imgur_Plugin',
      pushedAt: '2022-09-06T13:39:03Z',
    },
    {
      name: 'TouchPortal-MediaMonkey-Plugin',
      description: 'Plugin for Touch Portal to control Media Monkey',
      stars: 0,
      language: 'JavaScript',
      url: 'https://github.com/spdermn02/TouchPortal-MediaMonkey-Plugin',
      pushedAt: '2022-07-24T15:37:05Z',
    },
    {
      name: 'TouchPortal-Icons',
      description: 'TouchPortal Icons created by Spdermn02',
      stars: 0,
      language: null,
      url: 'https://github.com/spdermn02/TouchPortal-Icons',
      pushedAt: '2021-03-20T06:16:48Z',
    },
  ],
  released: [
    'TouchPortal_Discord_Plugin', 'TouchPortal-HardwareMonitor', 'TouchPortal-Dynamic-Icons',
    'TouchPortal_KeyboardMaestro_Plugin', 'TouchPortal_ITunes_Plugin', 'TouchPortal_Corsair_iCue',
    'TouchPortal_WebpageCapture_Plugin', 'TouchPortal_AdvancedHold_Plugin', 'TouchPortal_MessageKeyPress',
    'TouchPortal_StreamRaiders_Plugin', 'TouchPortal_Clownfish_VoiceChanger_Plugin', 'TouchPortal_Imgur_Plugin',
  ],
  featured: {
    stars: 20,
    description: 'Connect and build a Plugin with Node.JS using the touchportal-api',
  },
  npm: { downloads: 190, version: '4.0.0' },
};
